### ISSUE TITLE
wrong number of arguments in build_record

### ISSUE THREAD

**Issue by dandlezzz** [rails/protected_attributes#53] opened 2015-01-06 07:23 UTC
Hello, 
This may have been handled by https://github.com/rails/protected_attributes/pull/50. But even with my app pointed at master for protected_attributes and rails 4-2-stable. When I call build on a has_many_through relation, I get 

`ArgumentError (wrong number of arguments (2 for 1)):
  /Users/danielamiller/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-eb53536a1ccd/activerecord/lib/active_record/associations/through_association.rb:95:in build_record'
  /Users/danielamiller/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/protected_attributes-61e622368d66/lib/active_record/mass_assignment_security/associations.rb:72:in build_record'
  /Users/danielamiller/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/protected_attributes-61e622368d66/lib/active_record/mass_assignment_security/associations.rb:19:in build'
  /Users/danielamiller/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/protected_attributes-61e622368d66/lib/active_record/mass_assignment_security/associations.rb:55:in `build'`

A small caveat I am using the class_name option so it looks like 
has_many : foos, class_name: "Bar". 

Any help is greatly appreciated.

**Comment by rafaelfranca** [comment] 2015-01-06 14:01
Can you please provide a sample application that reproduces the error?

**Comment by dandlezzz** [comment] 2015-01-06 17:57
Updated to clarifiy that I am working with a has_many_though relationship and not just a has_many

**Comment by jGRUBBS** [comment] 2015-01-06 19:19
@rafaelfranca it looks like this merge in rails is most likely the culprit: https://github.com/rails/rails/commit/d9d4cd496fdb8b7b373c9b96337ddc8b8eec717e

As well when running the test suite there are 119 failures. `test_has_many_through_build_with_attr_accessible_attributes` is a failure for a test from the original fix for this issue. However, it is failing slightly differently than this example, leading me to believe that something else in Rails broke this before the newer commit number that @dandlezzz is running from: 
```
ArgumentError: wrong number of arguments (1 for 0)
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract_adapter.rb:271:in `initialize'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract_adapter.rb:271:in `new'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract_adapter.rb:271:in `substitute_at'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/relation.rb:99:in `block in substitute_values'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/relation.rb:98:in `each'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/relation.rb:98:in `each_with_index'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/relation.rb:98:in `substitute_values'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/relation.rb:58:in `insert'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/persistence.rb:521:in `_create_record'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/counter_cache.rb:139:in `_create_record'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/attribute_methods/dirty.rb:122:in `_create_record'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/callbacks.rb:306:in `block in _create_record'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:114:in `call'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:114:in `call'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:216:in `block in halting_and_conditional'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:87:in `call'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:87:in `run_callbacks'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/callbacks.rb:306:in `_create_record'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/timestamp.rb:57:in `_create_record'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/persistence.rb:501:in `create_or_update'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/callbacks.rb:302:in `block in create_or_update'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:114:in `call'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:114:in `call'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:166:in `block in halting'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:166:in `call'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:166:in `block in halting'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:216:in `call'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:216:in `block in halting_and_conditional'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:87:in `call'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activesupport-4.2.0.beta2/lib/active_support/callbacks.rb:87:in `run_callbacks'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/callbacks.rb:302:in `create_or_update'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/persistence.rb:120:in `save'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/validations.rb:36:in `save'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/attribute_methods/dirty.rb:21:in `save'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:284:in `block (2 levels) in save'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:345:in `block in with_transaction_returning_status'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:218:in `transaction'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:342:in `with_transaction_returning_status'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:284:in `block in save'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:299:in `rollback_active_record_state!'
    /Users/justin/.rvm/gems/ruby-2.0.0-p576/gems/activerecord-4.2.0.beta2/lib/active_record/transactions.rb:283:in `save'
    /Users/justin/Sites/protected_attributes/lib/active_record/mass_assignment_security/persistence.rb:46:in `create'
    /Users/justin/Sites/protected_attributes/test/attribute_sanitization_test.rb:76:in `setup'
```

**Comment by rafaelfranca** [comment] 2015-01-06 19:30
Make a lot of sense. This happened because we added da new `build_record` implementation that is not override by this gem. Mind to open a PR?

**Comment by jGRUBBS** [comment] 2015-01-06 20:59
@dandlezzz my PR referenced above will solve your issue. However, if you run rails from the released version of 4.2.0 and protected_attributes from master your app should run fine.

**Comment by rafaelfranca** [comment] 2015-03-16 20:49
Fixed by #64

**Closed by rafaelfranca** 2015-03-16 20:49 UTC

**Comment by adrianomitre** [comment] 2016-01-12 17:38
I am experiencing the exact same problem on 4.2.4

**Comment by brauliobo** [comment] 2016-01-22 21:47
same as @adrianomitre, works with ruby 2.2.3 but not with ruby 2.3.0

**Comment by lluchez** [comment] 2020-10-16 17:23
Seeing the same issue. It happens when doing `Model.new(attrs)` where `attrs` is present.
Additional info:
- Rails: 4.0.13
- Ruby: 2.3.8
- protected_attributes: tried all versions from 1.0.0 up to 1.1.4
